# Generated by Django 3.2.11 on 2022-02-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('dateCommissioned', models.DateField()),
                ('starsRating', models.IntegerField()),
                ('account_no', models.IntegerField()),
            ],
        ),
    ]
