# Generated by Django 3.2.11 on 2022-02-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseMgt_API_building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='careTaker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_caretaker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
