# Generated by Django 3.2.11 on 2022-02-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseMgt_API_house', '0002_house_tenant'),
        ('HouseMgt_API_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='HouseMgt_API_house.house'),
        ),
    ]
