# Generated by Django 3.2.11 on 2022-02-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseMgt_API_user', '0002_alter_user_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='room',
            new_name='user_room',
        ),
    ]
