# Generated by Django 3.2.11 on 2022-02-04 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HouseMgt_API_house', '0003_remove_house_tenant'),
        ('HouseMgt_API_user', '0003_rename_room_user_user_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HouseMgt_API_house.house'),
        ),
    ]
