# Generated by Django 3.2.11 on 2022-02-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseMgt_API_user', '0004_alter_user_user_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_room',
        ),
    ]
