version: 2.1
jobs:
  test-and-lint:
    docker:
      
      
    working_dictionary: ~/repo
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: lint
          command: pylint CoreShamiri/  CoreTherapy/
      - run:
          name: run tests
          command: python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint

