# Generated by Django 3.2.11 on 2022-02-04 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HouseMgt_API_building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('floor_no', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HouseMgt_API_building.building')),
            ],
        ),
    ]
