# Generated by Django 3.2.11 on 2022-02-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseMgt_API_house', '0002_house_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tenant',
        ),
    ]
