# Generated by Django 3.2.11 on 2022-02-04 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HouseMgt_API_house', '0003_remove_house_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='tenant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_tenant', to=settings.AUTH_USER_MODEL),
        ),
    ]
